# pull the official docker image
FROM python:3.10.14-slim

# set work directory
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy project
COPY . .

# Specify the command to run when the container starts
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]