version: '3.8'

services:

  backend:
    build: ../backend
    container_name: research-agents-backend
    restart: always
    env_file:
      - ../backend/.env.dev
    volumes:
      - ../backend:/app
    ports:
      - 8018:8000

networks:
  default:
    driver: bridge
