version: '3.8'

services:

  backend:
    build: ../backend
    container_name: lugaai-backend
    restart: always
    env_file:
      - ../backend/.env.dev
    volumes:
      - ../backend:/app
    ports:
      - 8018:8000

  dozzle:
    container_name: lugaai-monitor-dozzle
    restart: always
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always

networks:
  default:
    driver: bridge
